### ISSUE TITLE
Roadmap v0.0.1

### ISSUE THREAD

**Issue by huachaohuang** [photondb/photondb#1]
I am trying to cut the first patch version of the storage engine this month.

This version will include an in-memory Bw-tree implementation that can be used as a concurrent tree map. Most features are done so far, except for the merge SMO. I will postpone the merge SMO until we have implemented the persistent part.

Here are some tasks before the release:

- [x] Refactor the iterator interface
- [x] Do some benchmark
- [x] Improve README and other materials

**Comment by huachaohuang** [comment]
The crate `photondb-engine v0.0.1` has been published now. Let's start working on the persistent part before doing more optimizations.
