### ISSUE TITLE
Tracking issue for 0.0.3

### ISSUE THREAD

**Issue by huachaohuang** [photondb/photondb#279]
Planned release date: 2022.12.02

## Tree

- [ ] ~~Merge small pages~~

## Page Store

- [x] Improve space reclamation
  - [x] #280
  - [x] #282
- [x] Limit max write buffes
  - [x] #291
  - [x] #290
  - [x] #298
  - [x] #299
- [ ] Separate hot/cold pages
  - [ ] Detail design
  - [x] #308
  - [x] #322
  - [x] #307
  - [x] #314
  - [x] #317
  - [x] #319
  - [x] #328
  - [x] #329
  - [x] #333
- [ ] Dump summary periodically
- [ ] Page Read Cache
  - [x] #295
  - [x] #327
  - [x] #346
  - [ ] Avoid useless alloc in IO ops
  - [x] Export Cache/IO stats via table.stats()
  - [ ] Simulate test different replacement algorithms
- [ ] Compress PageFile data
   - [x] #330
   - [ ] Compress meta page(https://github.com/photondb/photondb/issues/261#issuecomment-1311763743)
- [ ] Remove unwrap/expect panic

**Comment by huachaohuang** [comment]
Since most features are already landed, I think we can release 0.0.3 today. @zojw @w41ter let me know if you have any more work to be included in this release. I will make a release later.
