### ISSUE TITLE
Tracking issues for develop PageStore

### ISSUE THREAD

**Issue by zojw** [photondb/photondb#5]
# Overview

The goals of the current milestone:

Set up an initial version runnable PageStore.

# Tasks

## Scheduled

- [x] WriteBuffer module
    - [x] #34
    - [x] #40
    - [x] #42
    - [x] #41
    - [x] #46
- [x] Version module
    - [x] #56
    - [x] #58
    - [x] #57
    - [x] #80
    - [x] #81
- [x] PageFile module
    - [x] #44
    - [x] #52
    - [x] #53
    - [x] #54
    - [x] #67
    - [x] #89
    - [x] #128
    - [x] #154
    - [ ] Avoid block file_builder when internal io_buf full
    - [ ] sync_all folder instead of sync_all new file
    - [ ] Pool io_buf avoid alloc buffer for each flush or read
- [ ] Manifest module
    - [x] #68
    - [x] #69
    - [x] Cleanup when open
    - [ ] Notify Cleanup job about obsoleted manifest
    - [x] #153
- [x] Flush job
    - [x] #135
    - [x] #61
    - [x] #62
    - [x] #63
- [x] Cleanup job
    - [x] #101
- [x] GC job
    - [x] #106
    - [x] #122
    - [x] #102
    - [x] #123
- [x] Photonio requirement
    - [x] open file with custom flags(to set O_DIRECT)
    - [x] let io_uring support ftruncate(2)
- [x] PageStore module
	- [x] #78
	- [x] #79
	- [x] #98
	- [x] #82
	- [x] #99
	- [x] #108
	- [x] #109

## Archived

- [x] Design public and module API
  - [x] #7
  - [x] #12
  - [x] #13
  - [x] #6
  - [x] #8
  - [x] #26
  - [x] #27
  - [x] #17
  - [x] #28

**Comment by huachaohuang** [comment]
I think we can close this and start a new development for 0.0.3.
